### ISSUE TITLE
Closing the pool after finish

### ISSUE THREAD

**Issue by Sahero** [graze/parallel-process#20]
Hi,

Is it possible to close or destroy pool after all the process finish?

Thank you

**Comment by h-bragg** [comment]
Hi,

So the pool is a bit of a misname I guess, there is no pool of processes handing around waiting to run stuff, it spawns and stops things as it needs, with an internal limit. There is no real concept of closing a pool in this sense.

However if you want to destroy the object you could do: (code from memory and not sure if it will work)

```php
$pool = new Pool([$run1,$run2]);
$pool->addListener(RunEvent::COMPLETED, function (RunEvent $runEvent) use (&$pool) {
    $pool = null;
});
$pool->start();
// do some async stuff
```

**Comment by Sahero** [comment]
Thanks mate, that makes sense. I will give it a try.
